### ISSUE TITLE
The Diamond SVG is cropped on both ends.

### ISSUE THREAD

**Issue by kevinolsson** [encharm/Font-Awesome-SVG-PNG#29]
Looking at Diamond from Fontawesome http://fortawesome.github.io/Font-Awesome/icon/diamond/
The one here is cropped.

**Comment by llwt** [comment]
The [credit card svgs](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/cc.svg) are cropped as well.

**Comment by Jelv** [comment]
The same for [Graduation cap](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/256/graduation-cap.png) in SVG and PNG.

**Comment by ThibaultR** [comment]
Same for [picture-o.svg](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/picture-o.svg) and [camera.svg](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/camera.svg) and probably a few others...

**Comment by FelisPhasma** [comment]
Also [weixin.svg](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/weixin.svg)

**Comment by sprinz** [comment]
Also every variant of cloud.svg

**Comment by konpa** [comment]
same for Behance

**Comment by osricmacon** [comment]
Its there for a lot of them. 
Anyone has any idea or quick fix?

**Comment by FelisPhasma** [comment]
There appears to be a lot of them. How about just scaling it down so it fits in the SVG?

**Comment by Nimdraug** [comment]
The issue is that it has been assumed that all font-awesome icons fit in a square, which is true for most of them, but there are quite a few of them that do not, as we have discovered.
Personally I don't think scaling them down is the answer because we need them to have roughly the same height for layout purposes etc. For instance I need the social icons to have the same height, and having the G+ icon be smaller would make things looks out of whack.
What I think should happen is that the view boxes should conform to the actual size of the icon. However, I don't know how easy that will be to work out in the generate script.

**Comment by Rush** [comment]
@Nimdraug fixed :) I removed the assumption of icons being square., although pixel-grid padding code will try to keep the originally-square icons to be still square.
